#!/bin/bash
echo "=== 部署脚本 ==="
echo ""
echo "请选择部署方式："
echo "1. 手动在 Vercel 控制台部署"
echo "2. 使用 Vercel CLI 部署（需要 token）"
echo ""
echo "=== 方式1: Vercel 控制台部署 ==="
echo "1. 访问: https://vercel.com/team_2irOQpexAmoDAhb0bUtOPpCO/deploy"
echo "2. 找到 'deploy' 项目"
echo "3. 点击 'Redeploy'"
echo ""
echo "=== 方式2: CLI 部署 ==="
echo "运行: npx vercel --prod --token=YOUR_TOKEN"
